# Generated by Django 4.2.5 on 2024-01-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
