# Generated by Django 4.2.5 on 2024-01-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewblog', '0003_alter_post_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(default='rock', max_length=100),
        ),
    ]
