# Generated by Django 4.2.5 on 2024-01-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynewblog', '0004_alter_post_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_category',
        ),
    ]
