# Generated by Django 4.2.5 on 2024-01-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynewblog', '0005_remove_post_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
