# Generated by Django 4.2.5 on 2024-01-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynewblog', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_category',
            new_name='post_author',
        ),
    ]
