# Generated by Django 4.2.5 on 2024-01-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynewblog', '0008_rename_post_category_post_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_author',
            new_name='post_catrgory',
        ),
    ]
